name:                code-wars-solutions
version:             0.1.0.0
github:              "githubuser/haskell"
license:             BSD3
author:              "Brian Parry"
maintainer:          "brianparry089@gmail.com"
copyright:           "2023 Brian Parry"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- quickcheck-instances
- QuickCheck
- servant-server
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - hspec
    - quickcheck-instances
    - QuickCheck
    - servant
    - servant-server
    - text
    - aeson
    - bytestring
    - containers
    - http-client
    - http-client-tls
    - http-types
    - servant
    - servant-client
    - servant-docs
    - servant-server
    - text
    - transformers
    - wai
    - warp

executables:
  helpers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - code-wars-solutions
    - servant
    - servant-server

tests:
  haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - code-wars-solutions
